---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: web-app
  template:
    metadata:
      labels:
        name: web-app
    spec:
      containers:
      - name: application
        image: 646904594762.dkr.ecr.eu-central-1.amazonaws.com/dev-ecr:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: web-secret
                key: db_username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: web-secret
                key: db_password
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "250Mi"
            cpu: "500m"