apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- namespace.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- ingress-controller.yaml
- ingress.yaml
