version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.12.0

jobs:
  build_and_push_image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          no-output-timeout: 10m
          path: ./
          region: AWS_REGION
          repo: web-app
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'
      - run:
          name: Install kustomize
          command: |
            curl -O -L https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.3.0/kustomize_kustomize.v4.3.0_linux_amd64
            sudo mv kustomize_kustomize.v4.3.0_linux_amd64 /usr/local/bin/kustomize
            sudo chmod u+x /usr/local/bin/kustomize
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: dev-eks-mCr8RKHg
          aws-region: $AWS_REGION
      - run:
          name: Deploy K8S resources
          command: |
            kustomize edit set image $AWS_ECR_ACCOUNT_URL/web-app:$CIRCLE_SHA1
            kustomize build . | kubectl apply -f -

workflows:
  version: 2.1
  build-deploy:
    jobs:
      # Build
      - build_and_push_image