version: 2.1

jobs:
   build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build image
          command: docker build .


workflows:
  version: 2.1
  build-deploy:
    jobs:

      # Build
      - build