version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  build_and_push_image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          no-output-timeout: 10m
          path: ./
          region: AWS_REGION
          repo: dev-ecr
          skip-when-tags-exist: false
          tag: 'latest'


workflows:
  version: 2.1
  build-deploy:
    jobs:
      # Build
      - build_and_push_image