version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.12.0

jobs:
  build_and_push_image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          no-output-timeout: 10m
          path: ./
          region: AWS_REGION
          repo: web-app
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'
      - run:
          name: Install kustomize
          command: |
            URL=https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.3.0/kustomize_v4.3.0_linux_amd64.tar.gz
            curl -L $URL | tar zx

            [ -w /usr/local/bin ] && SUDO="" || SUDO=sudo
            $SUDO chmod +x ./kustomize
            $SUDO mv ./kustomize /usr/local/bin
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: dev-eks-mCr8RKHg
          aws-region: $AWS_REGION
          install-kubectl: true
      - run:
          name: Deploy K8S resources to dev
          command: |
            cd dev
            kustomize edit set image $AWS_ECR_ACCOUNT_URL/web-app:$CIRCLE_SHA1
            kustomize build . | kubectl apply -f -

workflows:
  version: 2.1
  build-deploy:
    jobs:
      # Build
      - build_and_push_image